config:
  iac-sandbox-ha-python:simulateUnsupported: false
  iac-sandbox-ha-python:primaryRegion: us-east-1
  iac-sandbox-ha-python:secondaryRegion: us-west-2
  iac-sandbox-ha-python:dbUsername: 5c7fcc53-bccd-48f9-91d8-908ff82b4644
  iac-sandbox-ha-python:dbPassword: 5636f63b-8e18-46a0-a6bf-f1637e8b3fa5
