endpoint: "{{ lookup('env', 'LOCALSTACK_ENDPOINT') | default('http://localstack:4566', true) }}"
primary_region: us-east-1
secondary_region: us-west-2
object_source: /workspace/terraform/files/hello.txt
